{% set name = "einsteinpy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: 2e294b8c4ea8cbd248748cabec70bb9b

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - numpy
    - astropy
    - matplotlib-base
    - scipy >=1.0
    - sympy >=1.1
    - numba >=0.39
    - plotly >=4.0

test:
  imports:
    - {{ name }}
    - {{ name }}.integrators
    - {{ name }}.metric
    - {{ name }}.plotting
    - {{ name }}.utils

  requires:
    - pytest
    - pytest-benchmark

about:
  home: https://{{ name }}.org/
  license: MIT
  license_file: COPYING
  summary: Python for General Relativity!
  doc_url: https://docs.{{ name }}.org/
  dev_url: https://github.com/{{ name }}/{{ name }}/blob/master/docs/source/user_guide.rst

extra:
  recipe-maintainers:
    - shreyasbapat
    - ritzvik
    - spino17
    - masquerade0097
