travis:
  secure:
    BINSTAR_TOKEN: CGC9NfZQe32dyO51JFqAfzjp81YGYILVYbmHsoyJbeiGPuTeBGYWj2CiqYSDxVAri+ur1O1UXGpQL7l3uEMhBkiP0rrDpkLdgJFzP/vvLtYzGNQL7xcjck70qla7o41OtYUj8O3pB27KOFK7CQQIGExwKtZNnhxZ6RUIkoNsJJtdPchoXovx9V48PFXqowUAvi80W4WsDh13UGFWrgXQ60zGi9Dgin8FFmmrwSuUk20hAXaYccp2QO7JxjQXVu67tmdJLrn+Vs2zcYJqDA9WhHyV0FEo9BSUE4vMYcWkJRLy7Pj/TVa7/wTqZP7rGTW4oBB7KZUa4lTuHMKpLJvrzcVcK2A2wOcXud7V9NG10z7798Dcz/RujGgi2/YP3U33m7oGLAvGgsdPDRrpvoaDn6XAeEbIoLqZMsfX2PJhKR0bH3PHaGG2ZGxp6RB0RTOZS4eBAEMzpMpeGSaB1Q7orinVqbC6axK4syPQZJjqEPFGRKEkno9exM4Yq2cEid0fdp44jOyIvR6tzI/IjCWea51saPRG8ROBwCEh4XiRx7gv9i4RiUA5qMikjeGYaZA1KM+fzksmraAuOBH3ay9gMOUePCXXZgOmIVD8UxhEgdO+OBz6bN/n5lPyI0T3Wf2aZpHNY1NKPWmOByd6YpIqkKvJB5Fj3gxyUV7TmiJXv8Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
